defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      
baseurl: /outcomes/resources/bionic-eye
google-analytics-code: UA-49823608-1
gems: [bourbon, neat]